### PR TITLE
Check if <title> is set

### PR DESCRIPTION
**Pull request by CupOfTea696**
Check if there is a `<title>` node before grabbing its html.

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice! Could you also add a test for this?

**Comment by CupOfTea696** [comment]
I should remember to do that.

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
Your test worked, but I felt that the `setUp`-method became a litte bit too cluncky. so I refactored it a bit.

**Comment by CupOfTea696** [comment]
@freekmurze that's totally fine! I'm not used to writing tests (I know I should really start doing that but bad habits die hard I guess). To be fair, I only found out about testing and PHPUnit and stuff quite recently. #ThingsTheyDidntTeachUsAtSchool :/

**Comment by freekmurze** [comment]
@CupOfTea696 have fun learning all this testing stuff. It can all be a tad confusing, but do persist. 

Schools should indeed put some more focus on this subject.

**Comment by CupOfTea696** [comment]
@freekmurze yeah absolutely, it makes a lot of sense writing tests :)

**Pull request merged**
